language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - cd react-demo-app
  - npm install
  - npm test
  - npm run build
deploy:
  provider: heroku
  api_key: $HEKOKU_API_KEY
  app:
    master: react-hello-world123
    production: react-hello-world123